export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const PREPARATION_MESSAGE = 'PREPARATION_MESSAGE';

export const SET_AUTH = 'SET_AUTH';
export const SIGN_OUT = 'SIGN_OUT';
